from typing import Any

def color(G): ...
def is_bipartite(G): ...
def is_bipartite_node_set(G, nodes): ...
def sets(G, top_nodes: Any | None = ...): ...
def density(B, nodes): ...
def degrees(B, nodes, weight: Any | None = ...): ...
