from typing import Any

def latapy_clustering(G, nodes: Any | None = ..., mode: str = ...): ...

clustering = latapy_clustering

def average_clustering(G, nodes: Any | None = ..., mode: str = ...): ...
def robins_alexander_clustering(G): ...
