from typing import Any

def complete_bipartite_graph(n1, n2, create_using: Any | None = ...): ...
def configuration_model(
    aseq, bseq, create_using: Any | None = ..., seed: Any | None = ...
): ...
def havel_hakimi_graph(aseq, bseq, create_using: Any | None = ...): ...
def reverse_havel_hakimi_graph(aseq, bseq, create_using: Any | None = ...): ...
def alternating_havel_hakimi_graph(aseq, bseq, create_using: Any | None = ...): ...
def preferential_attachment_graph(
    aseq, p, create_using: Any | None = ..., seed: Any | None = ...
): ...
def random_graph(n, m, p, seed: Any | None = ..., directed: bool = ...): ...
def gnmk_random_graph(n, m, k, seed: Any | None = ..., directed: bool = ...): ...
