from typing import Any

def hopcroft_karp_matching(G, top_nodes: Any | None = ...): ...
def eppstein_matching(G, top_nodes: Any | None = ...): ...
def to_vertex_cover(G, matching, top_nodes: Any | None = ...): ...

maximum_matching = hopcroft_karp_matching

def minimum_weight_full_matching(G, top_nodes: Any | None = ..., weight: str = ...): ...
