from typing import Any

def to_networkx_graph(
    data, create_using: Any | None = ..., multigraph_input: bool = ...
): ...
def to_dict_of_lists(G, nodelist: Any | None = ...): ...
def from_dict_of_lists(d, create_using: Any | None = ...): ...
def to_dict_of_dicts(G, nodelist: Any | None = ..., edge_data: Any | None = ...): ...
def from_dict_of_dicts(
    d, create_using: Any | None = ..., multigraph_input: bool = ...
): ...
def to_edgelist(G, nodelist: Any | None = ...): ...
def from_edgelist(edgelist, create_using: Any | None = ...): ...
