import types
from typing import Any

def attach(
    module_name, submodules: Any | None = ..., submod_attrs: Any | None = ...
): ...

class DelayedImportErrorModule(types.ModuleType):
    def __init__(self, frame_data, *args, **kwargs) -> None: ...
    def __getattr__(self, x) -> None: ...

def lazy_import(fullname): ...
