from typing import Any

def cytoscape_data(G, attrs: Any | None = ..., name: str = ..., ident: str = ...): ...
def cytoscape_graph(
    data, attrs: Any | None = ..., name: str = ..., ident: str = ...
): ...
