from typing import Any

def tree_data(
    G, root, attrs: Any | None = ..., ident: str = ..., children: str = ...
): ...
def tree_graph(
    data, attrs: Any | None = ..., ident: str = ..., children: str = ...
): ...
