from typing import Any

def betweenness_centrality_subset(
    G, sources, targets, normalized: bool = ..., weight: Any | None = ...
): ...
def edge_betweenness_centrality_subset(
    G, sources, targets, normalized: bool = ..., weight: Any | None = ...
): ...
def betweenness_centrality_source(
    G, normalized: bool = ..., weight: Any | None = ..., sources: Any | None = ...
): ...
