from typing import Any

def closeness_centrality(
    G, u: Any | None = ..., distance: Any | None = ..., wf_improved: bool = ...
): ...
def incremental_closeness_centrality(
    G, edge, prev_cc: Any | None = ..., insertion: bool = ..., wf_improved: bool = ...
): ...
