from typing import Any

def group_betweenness_centrality(
    G, C, normalized: bool = ..., weight: Any | None = ..., endpoints: bool = ...
): ...
def prominent_group(
    G,
    k,
    weight: Any | None = ...,
    C: Any | None = ...,
    endpoints: bool = ...,
    normalized: bool = ...,
    greedy: bool = ...,
): ...
def group_closeness_centrality(G, S, weight: Any | None = ...): ...
def group_degree_centrality(G, S): ...
def group_in_degree_centrality(G, S): ...
def group_out_degree_centrality(G, S): ...
