from typing import Any

def global_reaching_centrality(G, weight: Any | None = ..., normalized: bool = ...): ...
def local_reaching_centrality(
    G, v, paths: Any | None = ..., weight: Any | None = ..., normalized: bool = ...
): ...
