from typing import Any

class _HeapElement:
    priority: Any
    element: Any
    def __init__(self, priority, element) -> None: ...
    def __lt__(self, other): ...
    def __gt__(self, other): ...
    def __eq__(self, other): ...
    def __hash__(self): ...
    def __getitem__(self, indx): ...
    def __iter__(self): ...

class MappedQueue:
    heap: Any
    position: Any
    def __init__(self, data=...) -> None: ...
    def __len__(self): ...
    def push(self, elt, priority: Any | None = ...): ...
    def pop(self): ...
    def update(self, elt, new, priority: Any | None = ...) -> None: ...
    def remove(self, elt) -> None: ...
