from typing import Any

def powerlaw_sequence(n, exponent: float = ..., seed: Any | None = ...): ...
def zipf_rv(alpha, xmin: int = ..., seed: Any | None = ...): ...
def cumulative_distribution(distribution): ...
def discrete_sequence(
    n,
    distribution: Any | None = ...,
    cdistribution: Any | None = ...,
    seed: Any | None = ...,
): ...
def random_weighted_sample(mapping, k, seed: Any | None = ...): ...
def weighted_choice(mapping, seed: Any | None = ...): ...
