from typing import Any

from networkx.utils import groups as groups

class UnionFind:
    parents: Any
    weights: Any
    def __init__(self, elements: Any | None = ...) -> None: ...
    def __getitem__(self, object): ...
    def __iter__(self): ...
    def to_sets(self) -> None: ...
    def union(self, *objects): ...
