from collections.abc import Generator
from typing import Any

def attracting_components(G) -> Generator[Any, None, None]: ...
def number_attracting_components(G): ...
def is_attracting_component(G): ...
