from collections.abc import Generator
from typing import Any

def connected_components(G) -> Generator[Any, None, None]: ...
def number_connected_components(G): ...
def is_connected(G): ...
def node_connected_component(G, n): ...
