from collections.abc import Generator
from typing import Any

def weakly_connected_components(G) -> Generator[Any, None, None]: ...
def number_weakly_connected_components(G): ...
def is_weakly_connected(G): ...
