from typing import Any

def triangles(G, nodes: Any | None = ...): ...
def average_clustering(
    G, nodes: Any | None = ..., weight: Any | None = ..., count_zeros: bool = ...
): ...
def clustering(G, nodes: Any | None = ..., weight: Any | None = ...): ...
def transitivity(G): ...
def square_clustering(G, nodes: Any | None = ...): ...
def generalized_degree(G, nodes: Any | None = ...): ...
