from typing import Any

def cut_size(G, S, T: Any | None = ..., weight: Any | None = ...): ...
def volume(G, S, weight: Any | None = ...): ...
def normalized_cut_size(G, S, T: Any | None = ..., weight: Any | None = ...): ...
def conductance(G, S, T: Any | None = ..., weight: Any | None = ...): ...
def edge_expansion(G, S, T: Any | None = ..., weight: Any | None = ...): ...
def mixing_expansion(G, S, T: Any | None = ..., weight: Any | None = ...): ...
def node_expansion(G, S): ...
def boundary_expansion(G, S): ...
