from typing import Any

def extrema_bounding(G, compute: str = ...): ...
def eccentricity(G, v: Any | None = ..., sp: Any | None = ...): ...
def diameter(G, e: Any | None = ..., usebounds: bool = ...): ...
def periphery(G, e: Any | None = ..., usebounds: bool = ...): ...
def radius(G, e: Any | None = ..., usebounds: bool = ...): ...
def center(G, e: Any | None = ..., usebounds: bool = ...): ...
def barycenter(
    G, weight: Any | None = ..., attr: Any | None = ..., sp: Any | None = ...
): ...
def resistance_distance(
    G, nodeA, nodeB, weight: Any | None = ..., invert_weight: bool = ...
): ...
