from collections.abc import Generator
from typing import Any

def is_eulerian(G): ...
def is_semieulerian(G): ...
def eulerian_circuit(
    G, source: Any | None = ..., keys: bool = ...
) -> Generator[Any, None, None]: ...
def has_eulerian_path(G, source: Any | None = ...): ...
def eulerian_path(
    G, source: Any | None = ..., keys: bool = ...
) -> Generator[Any, None, None]: ...
def eulerize(G): ...
