from collections.abc import Generator
from typing import Any

def tree_all_pairs_lowest_common_ancestor(
    G, root: Any | None = ..., pairs: Any | None = ...
) -> Generator[Any, None, None]: ...
def lowest_common_ancestor(G, node1, node2, default: Any | None = ...): ...
def all_pairs_lowest_common_ancestor(
    G, pairs: Any | None = ...
) -> Generator[None, None, Any]: ...
