from collections.abc import Generator
from typing import Any

def maximal_matching(G): ...
def is_matching(G, matching): ...
def is_maximal_matching(G, matching): ...
def is_perfect_matching(G, matching): ...
def min_weight_matching(G, maxcardinality: bool = ..., weight: str = ...): ...
def max_weight_matching(
    G, maxcardinality: bool = ..., weight: str = ...
) -> Generator[None, None, Any]: ...
