from collections.abc import Generator
from typing import Any

def is_simple_path(G, nodes): ...
def all_simple_paths(G, source, target, cutoff: Any | None = ...): ...
def all_simple_edge_paths(
    G, source, target, cutoff: Any | None = ...
) -> Generator[Any, None, Any]: ...
def shortest_simple_paths(
    G, source, target, weight: Any | None = ...
) -> Generator[Any, None, Any]: ...

class PathBuffer:
    paths: Any
    sortedpaths: Any
    counter: Any
    def __init__(self) -> None: ...
    def __len__(self): ...
    def push(self, cost, path) -> None: ...
    def pop(self): ...
