from typing import Any

def random_reference(
    G, niter: int = ..., connectivity: bool = ..., seed: Any | None = ...
): ...
def lattice_reference(
    G,
    niter: int = ...,
    D: Any | None = ...,
    connectivity: bool = ...,
    seed: Any | None = ...,
): ...
def sigma(G, niter: int = ..., nrand: int = ..., seed: Any | None = ...): ...
def omega(G, niter: int = ..., nrand: int = ..., seed: Any | None = ...): ...
