from typing import Any

def effective_size(G, nodes: Any | None = ..., weight: Any | None = ...): ...
def constraint(G, nodes: Any | None = ..., weight: Any | None = ...): ...
def local_constraint(G, u, v, weight: Any | None = ...): ...
