from typing import Any

def double_edge_swap(
    G, nswap: int = ..., max_tries: int = ..., seed: Any | None = ...
): ...
def connected_double_edge_swap(
    G, nswap: int = ..., _window_threshold: int = ..., seed: Any | None = ...
): ...
