from typing import Any

def is_tournament(G): ...
def hamiltonian_path(G): ...
def random_tournament(n, seed: Any | None = ...): ...
def score_sequence(G): ...
def is_reachable(G, s, t): ...
def is_strongly_connected(G): ...
