from collections.abc import Generator
from typing import Any

def triadic_census(G, nodelist: Any | None = ...): ...
def is_triad(G): ...
def all_triplets(G): ...
def all_triads(G) -> Generator[Any, None, None]: ...
def triads_by_type(G): ...
def triad_type(G): ...
def random_triad(G): ...
