from typing import Any

def degree_assortativity_coefficient(
    G, x: str = ..., y: str = ..., weight: Any | None = ..., nodes: Any | None = ...
): ...
def degree_pearson_correlation_coefficient(
    G, x: str = ..., y: str = ..., weight: Any | None = ..., nodes: Any | None = ...
): ...
def attribute_assortativity_coefficient(G, attribute, nodes: Any | None = ...): ...
def numeric_assortativity_coefficient(G, attribute, nodes: Any | None = ...): ...
