from collections.abc import Generator
from typing import Any

def node_attribute_xy(
    G, attribute, nodes: Any | None = ...
) -> Generator[Any, None, None]: ...
def node_degree_xy(
    G, x: str = ..., y: str = ..., weight: Any | None = ..., nodes: Any | None = ...
) -> Generator[Any, None, None]: ...
