from typing import Any

def modularity_matrix(G, nodelist: Any | None = ..., weight: Any | None = ...): ...
def directed_modularity_matrix(
    G, nodelist: Any | None = ..., weight: Any | None = ...
): ...
