from typing import Any

def greedy_modularity_communities(
    G, weight: Any | None = ..., resolution: int = ..., n_communities: int = ...
): ...
def naive_greedy_modularity_communities(
    G, resolution: int = ..., weight: Any | None = ...
): ...

# Names in __all__ with no definition:
#   _naive_greedy_modularity_communities
