from collections.abc import Generator
from typing import Any

def from_graph6_bytes(bytes_in) -> Generator[None, None, Any]: ...
def to_graph6_bytes(G, nodes: Any | None = ..., header: bool = ...): ...
def read_graph6(path): ...
def write_graph6(G, path, nodes: Any | None = ..., header: bool = ...): ...
