from collections.abc import Generator
from typing import Any

def generate_pajek(G) -> Generator[Any, None, None]: ...
def write_pajek(G, path, encoding: str = ...) -> None: ...
def read_pajek(path, encoding: str = ...): ...
def parse_pajek(lines): ...
