from typing import Any, NamedTuple

def is_k_edge_connected(G, k): ...
def is_locally_k_edge_connected(G, s, t, k): ...
def k_edge_augmentation(
    G, k, avail: Any | None = ..., weight: Any | None = ..., partial: bool = ...
) -> None: ...

class MetaEdge(NamedTuple):
    meta_uv: Any
    uv: Any
    w: Any
