from collections.abc import Generator
from typing import Any

def k_edge_components(G, k): ...
def k_edge_subgraphs(G, k): ...
def bridge_components(G) -> None: ...

class EdgeComponentAuxGraph:
    A: Any
    H: Any
    @classmethod
    def construct(EdgeComponentAuxGraph, G): ...
    def k_edge_components(self, k) -> None: ...
    def k_edge_subgraphs(self, k) -> Generator[Any, None, None]: ...
