from typing import Any

def astar_path(G, source, target, heuristic: Any | None = ..., weight: str = ...): ...
def astar_path_length(
    G, source, target, heuristic: Any | None = ..., weight: str = ...
): ...
