from typing import Any

def floyd_warshall_numpy(G, nodelist: Any | None = ..., weight: str = ...): ...
def floyd_warshall_predecessor_and_distance(G, weight: str = ...): ...
def reconstruct_path(source, target, predecessors): ...
def floyd_warshall(G, weight: str = ...): ...
