from collections.abc import Generator
from typing import Any

def dfs_edges(
    G, source: Any | None = ..., depth_limit: Any | None = ...
) -> Generator[Any, None, None]: ...
def dfs_tree(G, source: Any | None = ..., depth_limit: Any | None = ...): ...
def dfs_predecessors(G, source: Any | None = ..., depth_limit: Any | None = ...): ...
def dfs_successors(G, source: Any | None = ..., depth_limit: Any | None = ...): ...
def dfs_postorder_nodes(G, source: Any | None = ..., depth_limit: Any | None = ...): ...
def dfs_preorder_nodes(G, source: Any | None = ..., depth_limit: Any | None = ...): ...
def dfs_labeled_edges(
    G, source: Any | None = ..., depth_limit: Any | None = ...
) -> Generator[Any, None, None]: ...
