from typing import Any

def local_node_connectivity(G, source, target, cutoff: Any | None = ...): ...
def node_connectivity(G, s: Any | None = ..., t: Any | None = ...): ...
def all_pairs_node_connectivity(
    G, nbunch: Any | None = ..., cutoff: Any | None = ...
): ...
