from typing import Any

def randomized_partitioning(
    G, seed: Any | None = ..., p: float = ..., weight: Any | None = ...
): ...
def one_exchange(
    G, initial_cut: Any | None = ..., seed: Any | None = ..., weight: Any | None = ...
): ...
