from typing import Any

def caveman_graph(l, k): ...
def connected_caveman_graph(l, k): ...
def relaxed_caveman_graph(l, k, p, seed: Any | None = ...): ...
def random_partition_graph(
    sizes, p_in, p_out, seed: Any | None = ..., directed: bool = ...
): ...
def planted_partition_graph(
    l, k, p_in, p_out, seed: Any | None = ..., directed: bool = ...
): ...
def gaussian_random_partition_graph(
    n, s, v, p_in, p_out, directed: bool = ..., seed: Any | None = ...
): ...
def ring_of_cliques(num_cliques, clique_size): ...
def windmill_graph(n, k): ...
def stochastic_block_model(
    sizes,
    p,
    nodelist: Any | None = ...,
    seed: Any | None = ...,
    directed: bool = ...,
    selfloops: bool = ...,
    sparse: bool = ...,
): ...
def LFR_benchmark_graph(
    n,
    tau1,
    tau2,
    mu,
    average_degree: Any | None = ...,
    min_degree: Any | None = ...,
    max_degree: Any | None = ...,
    min_community: Any | None = ...,
    max_community: Any | None = ...,
    tol: float = ...,
    max_iters: int = ...,
    seed: Any | None = ...,
): ...
