from typing import Any

def gn_graph(
    n, kernel: Any | None = ..., create_using: Any | None = ..., seed: Any | None = ...
): ...
def gnr_graph(n, p, create_using: Any | None = ..., seed: Any | None = ...): ...
def gnc_graph(n, create_using: Any | None = ..., seed: Any | None = ...): ...
def scale_free_graph(
    n,
    alpha: float = ...,
    beta: float = ...,
    gamma: float = ...,
    delta_in: float = ...,
    delta_out: int = ...,
    create_using: Any | None = ...,
    seed: Any | None = ...,
): ...
def random_k_out_graph(n, k, alpha, self_loops: bool = ..., seed: Any | None = ...): ...
