from typing import Any

def margulis_gabber_galil_graph(n, create_using: Any | None = ...): ...
def chordal_cycle_graph(p, create_using: Any | None = ...): ...
def paley_graph(p, create_using: Any | None = ...): ...
