from typing import Any

def uniform_random_intersection_graph(n, m, p, seed: Any | None = ...): ...
def k_random_intersection_graph(n, m, k, seed: Any | None = ...): ...
def general_random_intersection_graph(n, m, p, seed: Any | None = ...): ...
